### ISSUE TITLE
Enchantment Extractor crashed game and crashes on load

### ISSUE THREAD

**Issue by FreeER** [Buuz135/Industrial-Foregoing#114]
Industrial Foregoing Version: 1.12.2-1.5.6-93
TeslaCoreLib Version: 1.12-1.0.11
Crashlog (If Any): (full) https://pastebin.com/ZLYtgjTA
(presumably useful snippet below explanation)

Not certain if this is part of the cause but I threw a stack of sticks into the enchantment applicator and a single book with 4 enchants on it and the entire stack was enchanted, I then threw that stack of sticks into the extractor and got 5 stacks of sticks, pulled out the stacks and then threw in one of the still enchanted stacks (now with fewer enchants) into the extractor... (the extractor won't accept enchanted books so I was trying to work around that since the applicator will apply any enchant to any item)

Used MCedit to delete the extractor and I can load the save again, I made a backup first but it's 247 MB... I'd guess I could prune the chunks in my (fairly small) base and get the size down that way but it's after midnight for me right now....

(assumed useful snippet)
// Uh... Did I do that?

Time: 12/8/17 12:01 AM
Description: Ticking block entity

java.lang.ClassCastException: net.minecraft.nbt.NBTTagEnd cannot be cast to net.minecraft.nbt.NBTTagCompound

	at com.buuz135.industrial.tile.magic.EnchantmentExtractorTile.performWork(EnchantmentExtractorTile.java:136)

	at net.ndrei.teslacorelib.tileentities.ElectricMachine.protectedUpdate(ElectricMachine.kt:280)

	at com.buuz135.industrial.tile.CustomElectricMachine.protectedUpdate(CustomElectricMachine.java:92)

	at net.ndrei.teslacorelib.tileentities.ElectricTileEntity.innerUpdate(ElectricTileEntity.kt:118)

	at net.ndrei.teslacorelib.tileentities.SidedTileEntity.func_73660_a(SidedTileEntity.kt:984)

	at net.minecraft.world.World.func_72939_s(World.java:1829)

	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)

	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)

	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)

	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)

	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)

	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.buuz135.industrial.tile.magic.EnchantmentExtractorTile.performWork(EnchantmentExtractorTile.java:136)
	at net.ndrei.teslacorelib.tileentities.ElectricMachine.protectedUpdate(ElectricMachine.kt:280)
	at com.buuz135.industrial.tile.CustomElectricMachine.protectedUpdate(CustomElectricMachine.java:92)
	at net.ndrei.teslacorelib.tileentities.ElectricTileEntity.innerUpdate(ElectricTileEntity.kt:118)
	at net.ndrei.teslacorelib.tileentities.SidedTileEntity.func_73660_a(SidedTileEntity.kt:984)

-- Block entity being ticked --
Details:
	Name: industrialforegoing:enchantment_extractor_tile // com.buuz135.industrial.tile.magic.EnchantmentExtractorTile
	Block type: ID #2654 (tile.industrialforegoing.enchantment_extractor // com.buuz135.industrial.tile.block.EnchantmentExtractorBlock)
	Block data value: 4 / 0x4 / 0b0100
	Block location: World: (178,64,274), Chunk: (at 2,4,2 in 11,17; contains blocks 176,0,272 to 191,255,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #2654 (tile.industrialforegoing.enchantment_extractor // com.buuz135.industrial.tile.block.EnchantmentExtractorBlock)
	Actual block data value: 4 / 0x4 / 0b0100
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1829)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)

-- Affected level --
Details:
	Level name: FreeER
	All players: 1 total; [EntityPlayerMP['FreeER'/497, l='FreeER', x=175.18, y=63.00, z=273.62]]
	Chunk stats: ServerChunkCache: 273 Drop: 0
	Level seed: -4422673103518024971
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (168,64,256), Chunk: (at 8,4,0 in 10,16; contains blocks 160,0,256 to 175,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 8725862 game time, 119247 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 32938 (now: false), thunder time: 72494 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Buuz135** [comment]
Update to latest version and should be fixed
