### ISSUE TITLE
Crash while clicking on the 'J' button in the latex processor

### ISSUE THREAD

**Issue by MatthiasMann** [Buuz135/Industrial-Foregoing#126]
Industrial Foregoing Version: industrialforegoing-1.12.2-1.5.10-98.jar
TeslaCoreLib Version: tesla-core-lib-1.12-1.0.11.jar
Crashlog (If Any): 

java.lang.IllegalArgumentException: Invalid ingredient found. Parameter Name: focus value Class: class net.minecraft.item.ItemStack Object: 1xtile.air@0
        at mezz.jei.util.ErrorUtil.checkIsValidIngredient(ErrorUtil.java:216)
        at mezz.jei.gui.Focus.checkInternal(Focus.java:45)
        at mezz.jei.gui.Focus.<init>(Focus.java:17)
        at mezz.jei.recipes.RecipeRegistry.createFocus(RecipeRegistry.java:175)
        at com.buuz135.industrial.jei.JEICustomPlugin.showUses(JEICustomPlugin.java:66)
        at com.buuz135.industrial.jei.JEIHelper.openBlockUses(JEIHelper.java:13)
        at com.buuz135.industrial.tile.CustomElectricMachine$1.clicked(CustomElectricMachine.java:84)
        at net.ndrei.teslacorelib.gui.ToggleButtonPiece.mouseClicked(ToggleButtonPiece.kt:62)
        at net.ndrei.teslacorelib.gui.BasicTeslaGuiContainer.func_73864_a(BasicTeslaGuiContainer.kt:85)
        at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
        at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
        at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
        at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
        at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
        at net.minecraft.client.main.Main.main(SourceFile:123)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by MatthiasMann** [comment]
[crash-2017-12-13_21.28.00-client.txt](https://github.com/Buuz135/Industrial-Foregoing/files/1556976/crash-2017-12-13_21.28.00-client.txt)

**Comment by Buuz135** [comment]
Did you move the tile?

**Comment by MatthiasMann** [comment]
Hmm - i could be - didn't exactly remember how I set up the machine. But the pack has the carry mod in it.

But it is very convenient to place the machine somewhere - see what it needs before putting it at it's final destination - esp as the manual / tooltip does not provide much besides a textual description.

**Comment by Buuz135** [comment]
I will assume that it happened while moving the machine, just dont move the machine.
