### ISSUE TITLE
[BUG] Plant Interactor crash when harvesting Pixelmon berries

### ISSUE THREAD

**Issue by Whathefrench** [Buuz135/Industrial-Foregoing#398]
Industrial Foregoing Version:  1.12.2-1.12.2 
TeslaCoreLib Version: 1.0.15 
Java Version: 1.8.0_51 64Bits
Crashlog:  
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.177.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.35.jar)
  ForgelinPlugin (Forgelin-1.7.4.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.18.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.1.9.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-84.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 7/23/18 2:13 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraft.entity.player.EntityPlayerMP.func_71110_a(EntityPlayerMP.java:989)
	at net.minecraft.entity.player.EntityPlayerMP.func_71120_a(EntityPlayerMP.java:984)
	at com.pixelmonmod.pixelmon.entities.pixelmon.drops.DropItemHelper.giveItemStackToPlayer(DropItemHelper.java:144)
	at com.pixelmonmod.pixelmon.entities.pixelmon.drops.DropItemHelper.giveItemStackToPlayer(DropItemHelper.java:103)
	at com.pixelmonmod.pixelmon.entities.pixelmon.drops.DropItemHelper.giveItemStackToPlayer(DropItemHelper.java:85)
	at com.pixelmonmod.pixelmon.entities.pixelmon.drops.DropItemHelper.giveItemStackToPlayer(DropItemHelper.java:57)
	at com.pixelmonmod.pixelmon.blocks.apricornTrees.BlockApricornTree.func_180639_a(BlockApricornTree.java:233)
	at com.buuz135.industrial.tile.agriculture.PlantInteractorTile.work(PlantInteractorTile.java:71)
	at com.buuz135.industrial.tile.WorkingAreaElectricMachine.performWork(WorkingAreaElectricMachine.java:91)
	at net.ndrei.teslacorelib.tileentities.ElectricMachine.protectedUpdate(ElectricMachine.kt:280)
	at com.buuz135.industrial.tile.CustomElectricMachine.protectedUpdate(CustomElectricMachine.java:98)
	at net.ndrei.teslacorelib.tileentities.ElectricTileEntity.innerUpdate(ElectricTileEntity.kt:118)
	at net.ndrei.teslacorelib.tileentities.SidedTileEntity.func_73660_a(SidedTileEntity.kt:991)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71110_a(EntityPlayerMP.java:989)
	at net.minecraft.entity.player.EntityPlayerMP.func_71120_a(EntityPlayerMP.java:984)
	at com.pixelmonmod.pixelmon.entities.pixelmon.drops.DropItemHelper.giveItemStackToPlayer(DropItemHelper.java:144)
	at com.pixelmonmod.pixelmon.entities.pixelmon.drops.DropItemHelper.giveItemStackToPlayer(DropItemHelper.java:103)
	at com.pixelmonmod.pixelmon.entities.pixelmon.drops.DropItemHelper.giveItemStackToPlayer(DropItemHelper.java:85)
	at com.pixelmonmod.pixelmon.entities.pixelmon.drops.DropItemHelper.giveItemStackToPlayer(DropItemHelper.java:57)
	at com.pixelmonmod.pixelmon.blocks.apricornTrees.BlockApricornTree.func_180639_a(BlockApricornTree.java:233)
	at com.buuz135.industrial.tile.agriculture.PlantInteractorTile.work(PlantInteractorTile.java:71)
	at com.buuz135.industrial.tile.WorkingAreaElectricMachine.performWork(WorkingAreaElectricMachine.java:91)
	at net.ndrei.teslacorelib.tileentities.ElectricMachine.protectedUpdate(ElectricMachine.kt:280)
	at com.buuz135.industrial.tile.CustomElectricMachine.protectedUpdate(CustomElectricMachine.java:98)
	at net.ndrei.teslacorelib.tileentities.ElectricTileEntity.innerUpdate(ElectricTileEntity.kt:118)
	at net.ndrei.teslacorelib.tileentities.SidedTileEntity.func_73660_a(SidedTileEntity.kt:991)

-- Block entity being ticked --
Details:
	Name: industrialforegoing:plant_interactor_tile // com.buuz135.industrial.tile.agriculture.PlantInteractorTile
	Block type: ID #2310 (tile.industrialforegoing.plant_interactor // com.buuz135.industrial.tile.block.PlantInteractorBlock)
	Block data value: 2 / 0x2 / 0b0010
	Block location: World: (-2,71,192), Chunk: (at 14,4,0 in -1,12; contains blocks -16,0,192 to -1,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #2310 (tile.industrialforegoing.plant_interactor // com.buuz135.industrial.tile.block.PlantInteractorBlock)
	Actual block data value: 2 / 0x2 / 0b0010
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [GCEntityPlayerMP['Whathefrench'/228, l='New World', x=-3.38, y=71.00, z=193.26]]
	Chunk stats: ServerChunkCache: 441 Drop: 0
	Level seed: -939532616833845192
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (0,64,192), Chunk: (at 0,4,0 in 0,12; contains blocks 0,0,192 to 15,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 73646 game time, 73646 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 92970 (now: false), thunder time: 89046 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

**Comment by zackeezy** [comment]
I talked to the Pixelmon devs and they seem to be implementing a fix in version 7.0.0 that looks for a fake player
