### ISSUE TITLE
[1.12.2] 1.11.1-206 - Strawregistry Crash

### ISSUE THREAD

**Issue by darkman1984** [Buuz135/Industrial-Foregoing#414]
Industrial Foregoing Version: 1.11.1-206
TeslaCoreLib Version: 1.0.15
Crashlog (If Any):` 
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: jackyy/integrationforegoing/integration/straw/StrawRegistryThermalFoundation$1
	at jackyy.integrationforegoing.integration.straw.StrawRegistryThermalFoundation.register(StrawRegistryThermalFoundation.java:35)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1164_StrawRegistryThermalFoundation_register_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:762)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: jackyy.integrationforegoing.integration.straw.StrawRegistryThermalFoundation$1
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 more
Caused by: java.lang.NoClassDefFoundError: com/buuz135/industrial/utils/strawhandlers/StrawHandlerBase
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 14 more
Caused by: java.lang.ClassNotFoundException: com.buuz135.industrial.utils.strawhandlers.StrawHandlerBase
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more `
Works fine with Version 105 and the old Tesla Lib 1.0.14

**Comment by Buuz135** [comment]
Update integration foregoing
