### ISSUE TITLE
Using Generators with Power Cells crashes game

### ISSUE THREAD

**Issue by rausrh** [Buuz135/Industrial-Foregoing#98]
Using IF generators with Power Cells causes game to crash.  
I've tried Petrified Fuel and Biofuel Generators. 
Log errors are similar to reported bug in RFTools (https://github.com/TechReborn/TechReborn/issues/1161)

Industrial Foregoing Version: 1.12.2-1.5.8-95
TeslaCoreLib Version: 1.12-1.0.11
Crashlog (If Any): 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mcjty.rftools.blocks.powercell.PowerCellTileEntity.getNetwork(PowerCellTileEntity.java:156)
	at mcjty.rftools.blocks.powercell.PowerCellTileEntity.receiveEnergyMulti(PowerCellTileEntity.java:481)
	at mcjty.rftools.blocks.powercell.PowerCellTileEntity.receiveEnergyFacing(PowerCellTileEntity.java:470)
	at mcjty.rftools.blocks.powercell.PowerCellTileEntity$1.receiveEnergy(PowerCellTileEntity.java:731)
	at net.ndrei.teslacorelib.energy.systems.ForgeEnergySystem$ReverseWrapper.givePower(ForgeEnergySystem.kt:68)
	at net.ndrei.teslacorelib.tileentities.ElectricGenerator.protectedUpdate(ElectricGenerator.kt:201)
	at net.ndrei.teslacorelib.tileentities.ElectricTileEntity.innerUpdate(ElectricTileEntity.kt:118)
	at net.ndrei.teslacorelib.tileentities.SidedTileEntity.func_73660_a(SidedTileEntity.kt:984)

-- Block entity being ticked --
Details:
	Name: industrialforegoing:petrified_fuel_generator_tile // com.buuz135.industrial.tile.generator.PetrifiedFuelGeneratorTile
	Block type: ID #2652 (tile.industrialforegoing.petrified_fuel_generator // com.buuz135.industrial.tile.block.PetrifiedFuelGeneratorBlock)
	Block data value: 4 / 0x4 / 0b0100
	Block location: World: (-247,68,264), Chunk: (at 9,4,8 in -16,16; contains blocks -256,0,256 to -241,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #2652 (tile.industrialforegoing.petrified_fuel_generator // com.buuz135.industrial.tile.block.PetrifiedFuelGeneratorBlock)
	Actual block data value: 4 / 0x4 / 0b0100

**Comment by Buuz135** [comment]
I think this is already fixed.
