### ISSUE TITLE
Client crash: MouseOver FluidContainer in FluidPump GUI

### ISSUE THREAD

**Issue by CJBok** [Buuz135/Industrial-Foregoing#99]
Industrial Foregoing Version: 1.12.2-1.5.9-96
TeslaCoreLib Version: 1.0.11 
Crashlog (If Any): [Crash location!](https://github.com/Buuz135/Industrial-Foregoing/blob/16ca0aff6ecac992c114a0e55bc54cf20c4f50a3/src/main/java/com/buuz135/industrial/tile/world/FluidPumpTile.java#L128)

```
java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:50)
	at com.buuz135.industrial.tile.world.FluidPumpTile$1.drawForegroundTopLayer(FluidPumpTile.java:128)
	at net.ndrei.teslacorelib.gui.BasicTeslaGuiContainer$drawGuiContainerForegroundLayer$2.invoke(BasicTeslaGuiContainer.kt:76)
	at net.ndrei.teslacorelib.gui.BasicTeslaGuiContainer$drawGuiContainerForegroundLayer$2.invoke(BasicTeslaGuiContainer.kt:20)
	at net.ndrei.teslacorelib.gui.BasicTeslaGuiContainer.drawPieces(BasicTeslaGuiContainer.kt:58)
	at net.ndrei.teslacorelib.gui.BasicTeslaGuiContainer.func_146979_b(BasicTeslaGuiContainer.kt:76)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:117)
	at net.ndrei.teslacorelib.gui.BasicTeslaGuiContainer.func_73863_a(BasicTeslaGuiContainer.kt:51)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:353)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by Thorton101** [comment]
Direwolf20 1.12.2 Version 1.1.0
Industrial foregoing Version : 1.12.2-1.5.6.93
[crash-2017-11-23_11.59.25-client.txt](https://github.com/Buuz135/Industrial-Foregoing/files/1498812/crash-2017-11-23_11.59.25-client.txt)
